server:
  port: 8081
  address: 127.0.0.1
  #默认立即关闭、graceful优雅关闭（待正在执行的用户完成操作后关闭）
  shutdown: graceful

spring:
  application:
    name: redisdemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssmdemo?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
#  config: classpath:logback-spring.xml
  level:
    root: debug
    com.zxk.study: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"
#  file:
#    name: my.log
#    path: ./logger