server:
  port: 8081
  address: 192.168.1.45
  #默认立即关闭、graceful优雅关闭（待正在执行的用户完成操作后关闭）
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 10
#  servlet:
#    context-path:
spring:
  application:
    name: jurisdictionmanagerdemo
#  mvc:
#    static-path-pattern: classpath:/static
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jurisdictiondemo?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#  web:
#    resources:
#      static-locations: classpath:/templates/


#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxk.study.module.dto

#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zxk.study.module.dto
logging:
  config: classpath:logback-spring.xml
#  level:
#    root: INFO
#    com.zxk.study: debug
#    com.zxk.study.mapper: trace
#    org.springframework: info
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"

